name: CICD
on:
  push:
    branches: [ "master" ]

jobs:

  build:

    runs-on: self-hosted-1

    steps:
    - uses: actions/checkout@v3
    - name: Remove Old Docker image
      run: docker rmi $(docker images | grep 'fyp_backend_restfulapi_image') || true
    - name: Build the Docker image
      run: docker build . --file Dockerfile 
    - name: Remove Old Docker Container
      run: docker rm fyp_backend_restfulapi_container || true
    - name: Depoly to Docker Container
      run: docker run -d --net fyp-net -p 3000:3000 --name fyp_backend_restfulapi_container fyp_backend_restfulapi_image
